### PR TITLE
Add missing icons (fixes #5)

### LINKED ISSUE #5: Missing Icons [elfinder 2.1.5x
Nice theme, but soem toolbar icons are missing (e.g. Preferences, Show Hidden items).
Maybe they could be added?

### PR DESCRIPTION
**Pull request by oeway**
This PR add missing icons to the theme.

Before this PR:
Screenshot 2020-03-17 at 15 34 00

After this PR:
Screenshot 2020-03-17 at 15 32 49

(PS: it's a bit hard to find the exact icon, but I think it's better than leave it empty.)

### CODE REVIEW

**Comment by oeway** [comment]
@lokothodida Great, thanks.

BTW, do you know how to make the fixed version available on jsdelivr via this url: https://cdn.jsdelivr.net/gh/lokothodida/elfinder-theme-windows-10/windows-10/css/theme.css

The above url is referred in the theme json: https://nao-pon.github.io/elfinder-theme-manifests/win10.json

And currently, the above url gives the old version. I can get the new version by add `@master` (https://cdn.jsdelivr.net/gh/lokothodida/elfinder-theme-windows-10@master/windows-10/css/theme.css ) but I think it would be great if you can make it the default.

**Comment by lokothodida** [comment]
I'm not sure how long the old version stays cached for on jsdelivr, but when I follow the base link I see the latest version. Are you able to see it now?

**Comment by oeway** [comment]
I just checked, it still give the old version for example: https://cdn.jsdelivr.net/gh/lokothodida/elfinder-theme-windows-10/windows-10/css/toolbar.css

Here I should see the newly added icons, but I don’t.

Also if you go to https://studio-42.github.io/elFinder (uses the above link for the themes ) and try to set the theme to windows10, it still give the old version.
Any further idea?

**Comment by lokothodida** [comment]
For me I see the new version on that link, so my guess is that the [caching server](https://www.cloudflare.com/learning/cdn/what-is-caching/) that's physically closest to me has updated but yours hasn't. jsdelivr [doesn't yet](https://www.jsdelivr.com/tools/purge) have a tool for purging the cache, and it's not in my control to be able to do that...so all I can say is use the `@master` suffix for now and hopefully the servers near to you get updated soon 🤞

**Comment by oeway** [comment]
Ok, thanks! Good to know.

**Pull request merged**
